class RscText;
class RscPicture;
class RscButton;
class RscListBox;
class RscListNBox;
// class RscXListBox;
// class RscTree;
// class RscSlider;
// class RscXSliderH;
// class RscActiveText;
// class RscActivePicture;
// class RscActivePictureKeepAspect;
// class RscStructuredText;
// class RscToolbox;
// class RscControlsGroup;
// class RscControlsGroupNoScrollbars;
// class RscControlsGroupNoHScrollbars;
// class RscControlsGroupNoVScrollbars;
// class RscButtonTextOnly;
// class RscButtonMenu;
class RscButtonMenuOK;
class RscButtonMenuCancel;
// class RscButtonMenuSteam;
// class RscMapControl;
// class RscMapControlEmpty;
// class RscCheckBox;
